"""add saved_joins table

Revision ID: 3dc1bc8b4426
Revises: 29ffa6203105
Create Date: 2026-09-14 20:42:13.453892

Day 17 — reusable multi-dataset join definitions. `datasets`/`joins`
are stored as JSONB rather than normalized (see app/models/saved_join.py
for the reasoning); no data backfill needed, this is a brand new table
with no existing rows.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3dc1bc8b4426'
down_revision: Union[str, Sequence[str], None] = '29ffa6203105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_joins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('datasets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('joins', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_saved_join_workspace_name')
    )
    op.create_index(op.f('ix_saved_joins_id'), 'saved_joins', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_joins_id'), table_name='saved_joins')
    op.drop_table('saved_joins')
    # ### end Alembic commands ###
